# Generated by Django 6.1.1 on 2026-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='SRI KRISHNA', max_length=120)),
                ('tagline', models.CharField(default='Fashion for Every Generation', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('address', models.TextField(default='Main Bazaar Road, Narasapur, Andhra Pradesh')),
                ('landmark', models.CharField(blank=True, default='Near Bus Stand', max_length=150)),
                ('phone', models.CharField(default='9876543210', max_length=15)),
                ('whatsapp', models.CharField(default='9876543210', max_length=15)),
                ('email', models.EmailField(blank=True, default='contact@srikrishnaclothing.in', max_length=254)),
                ('gstin', models.CharField(blank=True, default='37ABCDE1234F1Z5', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='srikrishna@upi', max_length=60)),
                ('invoice_prefix', models.CharField(default='SK', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('default_gst_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('business_hours', models.CharField(default='Mon - Sun: 9:30 AM - 9:30 PM', max_length=150)),
                ('google_maps_embed_url', models.URLField(blank=True, default='')),
                ('loyalty_points_per_100_rupees', models.PositiveIntegerField(default=2)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
