# Generated by Django 6.1.1 on 2026-09-18 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('previous_stock', models.IntegerField()),
                ('stock_added', models.IntegerField(default=0)),
                ('stock_sold', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField()),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('RETURN', 'Return'), ('EXCHANGE', 'Exchange'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Invoice / Purchase / Return number', max_length=60)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
