# Generated by Django 6.1.1 on 2026-09-18 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=30, unique=True)),
                ('return_type', models.CharField(choices=[('RETURN', 'Return'), ('EXCHANGE', 'Exchange')], default='RETURN', max_length=10)),
                ('resolution', models.CharField(choices=[('REFUND', 'Refund'), ('STORE_CREDIT', 'Store Credit'), ('EXCHANGED', 'Exchanged for another item')], default='REFUND', max_length=20)),
                ('reason', models.TextField()),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('exchange_variant', models.ForeignKey(blank=True, help_text='If this is an exchange, the new variant given to customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_return_items', to='catalog.productvariant')),
                ('original_sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns_exchanges.return')),
            ],
        ),
    ]
